### ISSUE TITLE
make removeIdle() as a public method

### ISSUE THREAD

**Issue by smelukov** [coopernurse/node-pool#100]

**Comment by smelukov** [comment]
now, removeIdle() is calling only when scheduleRemoveIdle() is called in release()

**Comment by sandfox** [comment]
Hey @smelukov,

How come you want to make `removeIdle` public? At the moment, it's usage is purely internal.

**Comment by smelukov** [comment]
What if the client can't release itself?
In these cases I would like to call `removeIdle` by myself for release all of expired clients

**Comment by sandfox** [comment]
If a resource is being used/borrowed (i.e it's been handed out because someone has called `pool.acquire`) then it will not be considered when checking for `idle` resources. For a resource to be considered idle it must first be in the available pool.

Calling `removeIdle` should have no effect on resources that are borrowed.

**Comment by sandfox** [comment]
I think what you are after is some kind of "Abandoned Object / Resource" functionality, so that the resource pool is capable of destroying objects that have been borrowed for too long or some other condition.

This is is do-able but probably not something I'm going to have time to look at any time soon.

Apache Commons Pool is probably a good place to look for implementation ideas.

**Comment by sandfox** [comment]
closing as duplicate of whats required for #88
