### ISSUE TITLE
Drain and clear can occur too early when autostart = true and min > 0

### ISSUE THREAD

**Issue by wildbillh** [coopernurse/node-pool#159]
If autostart = true and min > 0 and you call drain() and clear() right after createPool(), the connections may not get reaped and the node process may hang.

I know this is a pretty arcane case, but I bring it to your attention as this could be handled in one of the closing functions. This issue was identified in one of my test cases for a class that uses pg and generic-pool.

I currently handle this by testing the _factoryCreateOperations set size to see if it's greater than zero. If so, then I wait a discrete amount of time before calling drain. If there are no pending creates, I leave the value of timeout at 0. 

```javascript
close () {
        return new Promise( (resolve, reject) => {
            // check to see if there are pending creates. If so wait a little
            let timeout = 0;
            this._pool && this._pool._factoryCreateOperations && (this._pool._factoryCreateOperations.size > 0) && (timeout = this._FACTORY_CREATION_WAIT_PERIOD);
            this.waitFunction(timeout)
            .then ( () => {
                return this._pool.drain();
            })
            .then ( () => {
                return this._pool.clear();
            })
            .then ( () => {
                return resolve();
            })
            .catch( (err) => {
                return reject (err);
            })
        });
    }
```

**Comment by sandfox** [comment]
Oh wow, this is some awesome work and good detective skills. Whilst it's probably not something most people are going come across it's still a good thing to fix. I suspect there are some more states flags/checks I can drop in to prevent this happening.

is this easy to reproduce, and do you have a test case / some code I use?

**Comment by wildbillh** [comment]
I pulled out as much code as possible to reproduce it. The code as is, works with the 250 ms delay (waitFunction) before drain() call. If you remove waitFunction from the chain, the connections never get reaped. One possible solution would be to return a promise from createPool() when the pending creates are complete. This might be too much of a deviation from the existing interface. Other than that, it would have to happen in the drain/clear functions. 
```
let GenericPool = require('generic-pool');
let pg = require ('pg');


let dbConfig = {
    user: 'nodejs-test',
    host: 'localhost',
    port: 5432,
    password: 'nodejs-test',
    database: 'nodejs-test',
};

let poolConfig = {
    max: 10, // maximum size of the pool
    min: 2, // minimum size of the pool
    idleTimeoutMillis: 5000,
    acquireTimeoutMillis: 1000,
    autostart: true
};

const factory =
{
    create: () => {
        return new Promise(function (resolve, reject) {
            // get a new pg client
            let client = new pg.Client(dbConfig);
            // pg complains if you don't listen to the error response
            client.on('error', () => {
            });
            // connect to the client
            client.connect((err) => {
                if (err) {
                    return reject(err.message);
                }
                else {
                    return resolve(client);
                }
            })
        });
    },
    destroy: (client) => {
        return new Promise(function (resolve, reject) {
            client.end((err) => {
                if (err) {
                    return reject(err);
                }
                return resolve();
            })
        })
    }
};

let waitFunction = (timeout) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve();
        }, timeout);
    });
};

pool = GenericPool.createPool(factory, poolConfig);

console.log(`pending create connections = ${pool._factoryCreateOperations.size}`);
waitFunction(250).then( () => {
    return pool.drain();
})
.then ( () => {
    return pool.clear();
})
.then ( () => {
    console.log('normal exit');
})
.catch( (err) => {
    return reject (err);
});
```
BTW
Your module is very useful, which is why I'm interesting in contributing. 
BH

**Comment by wildbillh** [comment]
Sorry, closed it on accident.

**Comment by sandfox** [comment]
I'm glad you are finding it useful :-) 

Thanks for the extra information and that code. I'll try to get to work on this in the next couple of days and make up a test or two for it.
Originally this module just exported a constructor function so returning a Promise from creating the pool wasn't do-able (at least as far as I could tell).

**Comment by sandfox** [comment]
notes to self:

The problem here seems to be that `clear` only operates on currently existing resources, and does not look at any any `factory.create` operations in progress. 

I think the quick-ish fix to this is to expand the scope of `pool.clear` such that it will also wait for and destroy any resources created by any `factory.create` operations in progress. I can see some obvious problems where the pool would never clear if a `factory.create` operations always rejected but thats outside the scope of this issue and wider problem to solve.


Slightly bigger picture solution is probably to make some kind of `pool.stop` method which handles all elements of shutting down a pool gracefully (and maybe also a hard stop option which just stops ditches waiting clients and shuts down as fast as possible without actually crashing).

**Comment by sandfox** [comment]
The solution ended up being as simple as making `clear` wait for `factory.create` calls to finish.

> I can see some obvious problems where the pool would never clear if a factory.create operations always rejected but thats outside the scope of this issue and wider problem to solve.
this ended up a non problem because when a rejected `factory.create` triggers `dispense` which will only request a new resource be created if there is demand. If the pool is "drained" then dispense will never trigger another `resource.create` call.

As far as I can tell `pool.drain` followed by `pool.clear` should now always  allow the pool to close and not leave any resources floating about.

**Comment by vlapo** [comment]
Hi @sandfox. I think this issue is actual again in last version of node-pool. We noticed hanging resources of DB connections in mssql library (using node-pool).

After little investigation I think that waiting for `factory.create` is not enough because after this promise is resolved, adding to `this._availableObjects` is not finished yet. So newly created resource will be not destroyed.

https://github.com/coopernurse/node-pool/blob/72b31a434c7b05ad879b2ace9830a9aa9fbba002/lib/Pool.js#L306-L320

I think `this._handleNewResource(resource);` is handled in parallel with destroy so resource is not available in `this._availableObjects` in moment of destroying.

Possible solution?:
```typescript
_createResource() {
    // An attempt to create a resource
    const factoryPromise = this._factory.create();
    const wrappedFactoryPromise = this._Promise.resolve(factoryPromise).then(resource => {
        this._handleNewResource(resource);
        return null;
      })
      .catch(reason => {
        this.emit(FACTORY_CREATE_ERROR, reason);
        this._dispense();
      });;

    this._trackOperation(wrappedFactoryPromise, this._factoryCreateOperations);
  }
```

**Comment by vlapo** [comment]
@sandfox Did you have time check this issue?

**Comment by sandfox** [comment]
not yet, but I'll try and get to it this week. If you could knock up some kind of test case or something that would really helpful

**Comment by vlapo** [comment]
I think this is minimal possible reproduction. My solution from previous comment resolve this issue but another tests failed. Will check why but maybe you will know better in shorter time.  

Test just delay create method sometime.`drain` do not wait to the end of creation process.
```javascript
const tap = require("tap");
const createPool = require("../").createPool;
const utils = require("./utils");
const ResourceFactory = utils.ResourceFactory;

class ResourceFactoryDelayCreateEachSecond {
    constructor() {
        this.callCreate = 0;
        this.created = 0;
        this.destroyed = 0;
        this.bin = []
    }

    create() {
        const that = this;
        return new Promise((resolve) => {
            if(that.callCreate%2 === 0) {
                setTimeout(function () {
                    resolve({ id: that.created++ });
                }, 100);
            } else {
                resolve({ id: that.created++ });
            }
            that.callCreate++;
        })
    }

    validate() {
        return Promise.resolve(true);
    }

    destroy(resource) {
        this.destroyed++;
        this.bin.push(resource);
        return Promise.resolve();
    }
}

tap.test("tests drain clear with autostart and min > 0", function (t) {
    const count = 5;
    let acquired = 0;

    const resourceFactory = new ResourceFactoryDelayCreateEachSecond();
    const config = {
        max: 10,
        min: 5,
        evictionRunIntervalMillis: 500,
        idleTimeoutMillis: 30000,
        testOnBorrow: true,
        autostart: true
    };
    const pool = createPool(resourceFactory, config);

    return pool.drain()
        .then(function () {
            return pool.clear();
        })
        .then(function () {
            t.equal(resourceFactory.created, resourceFactory.destroyed)
        })
        .then(function () {
            t.end();
        });
});
```

**Comment by sandfox** [comment]
ah sorry!

**Comment by sandfox** [comment]
Ok, I've tried running that test above a bunch of times against the current master and I can't get it to fail at all no matter how I change the timings and brute force it. That said I can see the general problem of where the accounting happens in relation to the operations/transactions (treating a `promise` as a transaction here because of how async boundaries work). I'll need to think about this a little bit more but I suspect that I'll need to rejig all the operation tracking slightly so that we're not doing the accounting in one promise and moving the resources in another.

**Comment by vlapo** [comment]
> Ok, I've tried running that test above a bunch of times against the current master and I can't get it to fail at all no matter how I change the timings and brute force it.

Please try node v 10. I just realize it is passing in node 8 but failed every time on node 10.

**Comment by sandfox** [comment]
@vlapo got a fix in #250 !

**Comment by vlapo** [comment]
Great @sandfox! I tested this branch in our large test set and I see no hanging resources now. 

When do you plan release new version with this fix ? :-)

**Comment by sandfox** [comment]
@vlapo done as v3.6.0 - https://www.npmjs.com/package/generic-pool/v/3.6.0
