### ISSUE TITLE
Did we release client when .acquire() has an err?

### ISSUE THREAD

**Issue by muyoucun557** [coopernurse/node-pool#182]
```
pool.acquire( function( err, client){
       if(err){
               return  release(client);    //?
       }
       // ......
       return release(client);
} );
```

**Comment by sandfox** [comment]
Hi there!
I'm going to assume you are using `generic-pool` v2 and not v3 (let me know if I am wrong).
If your callback receives an `err` then `client` will be `undefined` / `null` so you should not call `release(client)` because there is no client to release.

e.g

pool.acquire( function( err, client){
       if(err){
               // log something, or whatever :-)
               return
       }
       // ......
       return pool.release(client);
} );
