### ISSUE TITLE
Destroy resource after acquiring N times

### ISSUE THREAD

**Issue by hyzyla** [coopernurse/node-pool#255]
Is it possible to destroy resource after acquiring resource N times?

**Comment by sandfox** [comment]
There's nothing specifically in generic-pool that does this. However you might be able to implement something by adding a `validate` function to your [factory](https://github.com/coopernurse/node-pool#createpool) object you supply to `createPool`. You might be able to add a "useCount" property to your resources, thats gets incremented when you use it, and then in your validate function you could check that.  Otherwise you could add your own check before you return a resource to the pool. This check would look at the count and then `release` or `destroy` as appropriate.

**Comment by hyzyla** [comment]
Thanks, a lot!
