### ISSUE TITLE
Replace test library

### ISSUE THREAD

**Issue by sandfox** [coopernurse/node-pool#75]
The current test library has been depreciated for around 3 years but somehow still works. We should probably replace it with something maintained like tap or lab etc before it gets broken by a new release of node.

Open to suggestions or PRs for this. It's going to be a fair chunk of work to rewrite everything I suspect.

**Comment by felixfbecker** [comment]
@sandfox I'm trying to take a shot at it because my other PR is finished but I cannot run the expresso tests on Windows. However I don't understand the tests at all, some inline documents would have been helpful. There is no such thing as `beforeExit` and mocha, instead you call `done` with either an error or without one for async tests. The way you iterate synchronously with a `for` loop and then trigger async actions and the assert synchronously doesn't make sense to me...

Maybe you have some input, otherwise I will just take the existing test descriptions and write new ones for them, make them pass on the current version and then test against my prototype-PR.

**Comment by felixfbecker** [comment]
But I'm not even sure what _expands to max limit_ even means - what is _it_ in this context?

**Comment by felixfbecker** [comment]
Btw mocha needs at least Node 0.8

**Comment by sandfox** [comment]
Ok, I'll have a look and see if I shed any further light on that stuff and drop it here

I'm totally fine with dropping testing for everything pre-0.8 - as long as the new tests pass I'm happy with line of reasoning that we haven't broken backwards compatibility for library consumers (which ever ones are still out there on old skool node versions), and when the "class" stuff lands, as long as the tests still pass then _in theory_ we still won't have broken b/c.

**Comment by sandfox** [comment]
done in v3
