### ISSUE TITLE
generic-pool maxConnections likes multiple used in mysql with node v.11.x 

### ISSUE THREAD

**Issue by gse7en2012** [coopernurse/node-pool#89]
hi. Recently I found a problem.
I am using pm2 V0.12.3 and node v0.11.12. I found out that when using cluster mode in pm2 , generic-pool database connections=node instances* pool.maxConnections. 
But in fork mode, generic-pool maxConnections works well .
For example, my pool config setting maxConnections=10,then i run "pm2 start index.js -i 10" that i find the mysql conncetions=10*10. And run likes "pm2 start index.js" , mysql connctions=10.
When using v0.10.28 and pm2 0.8.3 do not have this problem before. all the node instances share the pool maxConnections . 
So I'm confused， is that node v0.11.x's new cluster module cause the problem?

**Comment by sandfox** [comment]
Sorry it's taken me a little while to reply...


By itself the pool module has no mechanism/ability to share state across different processes so each process will be running it's own separate instance of the pool and therefore each process therefore will be able to create up to the `maxConnections` number of resources because it has no idea what is happening in any other process.


>When using v0.10.28 and pm2 0.8.3 do not have this problem before. all the node instances share the pool maxConnections . 

Assuming this is in "fork mode" I'm not sure how that is working, or if pm2 is really starting 10 process, or if it is starting 10 processes but only one of them is actually running the pool.

Is there any demo code or actual examples you could link/gist to?

**Comment by gse7en2012** [comment]
ok. i see.  thx very much

**Comment by sandfox** [comment]
I'm going to close this, but feel free to open it up again if you have any more questions
